[[redirects]]
  from = "http://localhost:3000"
  to = "https://money-tracker0.netlify.app"
  status = 200
  force = true

[[redirects]]
  from = "http://localhost:3000/transactions"
  to = "https://money-tracker0.netlify.app/transactions"
  status = 200
  force = true